### ISSUE TITLE
cape not showing up (java.lang.NoSuchFieldException: playerInfo)

### ISSUE THREAD

**Issue by ItaySharon** [jadar/DeveloperCapes#41]
hi I getting this error:java.lang.NoSuchFieldException: playerInfo
Log:
[Start]
[15:40:12] [Client thread/ERROR] [DevCapes]: Setting cape ResourceLocation failed!
[15:40:12] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.NoSuchFieldException: playerInfo
[15:40:12] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.Class.getDeclaredField(Class.java:2062)
[15:40:12] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.jadarstudios.developercapes.cape.StaticCape.loadTexture(StaticCape.java:44)
[15:40:12] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.jadarstudios.developercapes.RenderEventHandler.renderPlayer(RenderEventHandler.java:39)
[15:40:12] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_6_RenderEventHandler_renderPlayer_Pre.invoke(.dynamic)
[15:40:12] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:55)
[15:40:12] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:138)
[15:40:12] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.renderer.entity.RendererLivingEntity.func_76986_a(RendererLivingEntity.java:89)
[15:40:12] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.renderer.entity.RenderPlayer.func_180596_a(SourceFile:58)
[15:40:12] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(SourceFile:19)
[15:40:12] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.renderer.entity.RenderManager.func_147939_a(RenderManager.java:370)
[15:40:12] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.renderer.entity.RenderManager.func_147936_a(RenderManager.java:327)
[15:40:12] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.renderer.entity.RenderManager.func_147937_a(RenderManager.java:294)
[15:40:12] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:631)
[15:40:12] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1294)
[15:40:12] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1207)
[15:40:12] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1032)
[15:40:12] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1049)
[15:40:12] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:345)
[15:40:12] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.main.Main.main(SourceFile:120)
[15:40:12] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[15:40:12] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[15:40:12] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[15:40:12] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.reflect.Method.invoke(Method.java:483)
[15:40:12] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[15:40:12] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[End]

Links:
JSON:http://itaysharon.esy.es/account/host/scubadivecapes/scubadivecapes.txt
PNG:http://itaysharon.esy.es/account/host/scubadivecapes/dive_cape.png

**Comment by jadar** [comment]
Looks like mappings or method names changed. What version of Minecraft are you trying to use?

**Comment by ItaySharon** [comment]
1.8 mmdanggg2's version

**Comment by Wehavecookies56** [comment]
mmdanggg2 didn't account for the obfuscated names for the fields he used in reflection. So it only works in the dev workspace

**Comment by ItaySharon** [comment]
1.8?

**Comment by ItaySharon** [comment]
download?

**Comment by Wehavecookies56** [comment]
Yes it's in 1.8, it's in my repo named "Kingdom-Keys-Re-coded"

**Comment by ItaySharon** [comment]
thx @Wehavecookies56 testing and closing!

**Comment by ItaySharon** [comment]
I have java error:[The type HDImageBuffer must implement the inherited abstract method IImageBuffer.skinAvailable()]
in class:HDImageBuffer

**Comment by ItaySharon** [comment]
and The method func_152634_a() of type HDImageBuffer must override or implement a supertype method

**Comment by Wehavecookies56** [comment]
Ah yes, the method name changed for func_152634_a() to skinAvailable() in HDImageBuffer

**Comment by ItaySharon** [comment]
so what to do?

**Comment by Wehavecookies56** [comment]
Change func_152634_a to skinAvailable

**Comment by ItaySharon** [comment]
Ok!

**Comment by ItaySharon** [comment]
testing...

**Comment by Wehavecookies56** [comment]
I just realised you are probably on an older version of forge, As I had to change skinAvailable to func_152634_a on the latest.

**Comment by ItaySharon** [comment]
using forge src latest(1.8-Forge11.14.0.1299)

**Comment by Wehavecookies56** [comment]
The latest is 11.14.3.1491

**Comment by ItaySharon** [comment]
sorry I meant other version (copied from the game, not src)
btw WORKING!!!

**Comment by ItaySharon** [comment]
THX @Wehavecookies56
